apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ./cd-set-images/
  - ./set-lco-karpenter-attrs/

resources:
  - ./ns/
  - ./base-patched/
  - ./ing-server/
  - ./sealedsecrets/

namespace: staging-mop
