apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ./cd-set-images/
  - ./set-lco-karpenter-attrs/

resources:
  - ./ns/
  - ./base-patched/
  - ./ing-server/
  - ./sealedsecrets/
  - ./postgres/
  - ./replacement-envfrom.yaml

namespace: staging-mop

configMapGenerator:
  - name: env
    behavior: merge
    literals:
      - DB_HOST=db-rw.staging-mop.svc
      - DB_NAME=mop
      - DB_USER=mop
      - DB_PORT=5432
      - AWS_S3_BUCKET=mop-dev-lco-global

secretGenerator:
  - name: db
    behavior: create
    type: kubernetes.io/basic-auth
    literals:
      - username=mop
      - password=mop

replacements:
  - source:
      kind: ReplacementSource
      name: envfrom
      fieldPath: data.envFrom
    targets:
      - select:
          kind: Deployment
        fieldPaths:
          - spec.template.spec.initContainers.*.envFrom
          - spec.template.spec.containers.*.envFrom
      - select:
          kind: CronJob
        fieldPaths:
          - spec.jobTemplate.spec.template.spec.containers.*.envFrom
  - source:
      kind: ReplacementSource
      name: envfrom
      fieldPath: data.dbPassValueFrom
    targets:
      - select:
          kind: Deployment
          name: server
        fieldPaths:
          - spec.template.spec.initContainers.*.env.[name=DB_PASS].valueFrom
          - spec.template.spec.containers.*.env.[name=DB_PASS].valueFrom
        options:
          create: true
      - select:
          kind: CronJob
        fieldPaths:
          - spec.jobTemplate.spec.template.spec.containers.*.env.[name=DB_PASS].valueFrom
        options:
          create: true

patches:
  - target:
      kind: CronJob
    patch: |-
      apiVersion: ignored
      kind: CronJob
      metadata:
        name: ignored
      spec:
        suspend: true

  - target:
      kind: Deployment
      name: server
    patch: |-
      apiVersion: ignored
      kind: Deployment
      metadata:
        name: server
      spec:
        template:
          spec:
            initContainers:
              - name: check-db-ready
              - name: apply-db-migrations
                resources:
                  limits:
                    memory: 2Gi
              - name: django-collectstatic
                resources:
                  limits:
                    memory: 2Gi
            containers:
              - name: default
                resources:
                  limits:
                    cpu: "2"
                    memory: 2Gi
                  requests:
                    cpu: 400m
                    memory: 768Mi
