apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ./cd-set-images/
  - ./set-lco-karpenter-attrs/

resources:
  - ./ns/
  - ./base-patched/
  - ./ing-server/
  - ./sealedsecrets/
  - ./replacement-envfrom.yaml

namespace: staging-mop

replacements:
  - source:
      kind: ReplacementSource
      name: envfrom
      fieldPath: data.envFrom
    targets:
      - select:
          kind: Deployment
        fieldPaths:
          - spec.template.spec.initContainers.*.envFrom
          - spec.template.spec.containers.*.envFrom
      - select:
          kind: CronJob
        fieldPaths:
          - spec.jobTemplate.spec.template.spec.containers.*.envFrom

patches:
  - target:
      kind: CronJob
    patch: |-
      apiVersion: ignored
      kind: CronJob
      metadata:
        name: ignored
      spec:
        suspend: true
