apiVersion: builtin
kind: PatchTransformer
metadata:
  name: antares-64cbg75k7g
  namespace: staging-mop
patch: '[{"op": "replace", "path": "/metadata/name", "value": "antares-64cbg75k7g"}]'
target:
  group: ""
  version: ""
  kind: Secret
  name: antares
  namespace: staging-mop
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: atlas-8f9dbb42kh
  namespace: staging-mop
patch: '[{"op": "replace", "path": "/metadata/name", "value": "atlas-8f9dbb42kh"}]'
target:
  group: ""
  version: ""
  kind: Secret
  name: atlas
  namespace: staging-mop
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: aws-5kbh8hk29t
  namespace: staging-mop
patch: '[{"op": "replace", "path": "/metadata/name", "value": "aws-5kbh8hk29t"}]'
target:
  group: ""
  version: ""
  kind: Secret
  name: aws
  namespace: staging-mop
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: django-td6dm2tb4k
  namespace: staging-mop
patch: '[{"op": "replace", "path": "/metadata/name", "value": "django-td6dm2tb4k"}]'
target:
  group: ""
  version: ""
  kind: Secret
  name: django
  namespace: staging-mop
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: gemini-b754mtghd8
  namespace: staging-mop
patch: '[{"op": "replace", "path": "/metadata/name", "value": "gemini-b754mtghd8"}]'
target:
  group: ""
  version: ""
  kind: Secret
  name: gemini
  namespace: staging-mop
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: isra-cb2dfdc848
  namespace: staging-mop
patch: '[{"op": "replace", "path": "/metadata/name", "value": "isra-cb2dfdc848"}]'
target:
  group: ""
  version: ""
  kind: Secret
  name: isra
  namespace: staging-mop
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: lco-7bb8hbdkh2
  namespace: staging-mop
patch: '[{"op": "replace", "path": "/metadata/name", "value": "lco-7bb8hbdkh2"}]'
target:
  group: ""
  version: ""
  kind: Secret
  name: lco
  namespace: staging-mop
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: tsn-26bc5hg2gb
  namespace: staging-mop
patch: '[{"op": "replace", "path": "/metadata/name", "value": "tsn-26bc5hg2gb"}]'
target:
  group: ""
  version: ""
  kind: Secret
  name: tsn
  namespace: staging-mop
