apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/

patches:
  - target:
      kind: CronJob
    patch: |-
      apiVersion: ignored
      kind: CronJob
      metadata:
        name: ignored
        annotations:
          set-karpenter-attrs.kpt.lco.earth/provisioner: "dev-jobs-big"
